// Mock data for demo mode
import type { Employee, MediaGroup, StorageAccountWithStats, MediaWithDetails } from '../types';

export const mockEmployee: Employee = {
    id: '1',
    email: 'admin@company.com',
    full_name: 'Admin User',
    role: 'admin',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
};

export const mockStorageAccounts: StorageAccountWithStats[] = [
    {
        id: 'sa-1',
        name: 'Primary CDN (Cloudinary)',
        provider: 'cloudinary',
        is_default: true,
        is_active: true,
        max_file_size_mb: 100,
        allowed_types: ['image', 'video'],
        created_by: '1',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        media_count: 1247,
        total_size_bytes: 2547896320,
        last_health_check: new Date().toISOString(),
        health_status: 'healthy',
    },
    {
        id: 'sa-2',
        name: 'Archive Storage (R2)',
        provider: 'r2',
        bucket_name: 'media-archive',
        region: 'auto',
        is_default: false,
        is_active: true,
        max_file_size_mb: 500,
        allowed_types: ['image', 'video', 'document', 'other'],
        created_by: '1',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        media_count: 3892,
        total_size_bytes: 15478963200,
        last_health_check: new Date().toISOString(),
        health_status: 'healthy',
    },
    {
        id: 'sa-3',
        name: 'Backup (S3)',
        provider: 's3',
        bucket_name: 'company-backups',
        region: 'us-east-1',
        is_default: false,
        is_active: true,
        max_file_size_mb: 1000,
        allowed_types: ['image', 'video', 'document', 'other'],
        created_by: '1',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        media_count: 856,
        total_size_bytes: 8547896320,
        last_health_check: new Date(Date.now() - 300000).toISOString(),
        health_status: 'degraded',
    },
];

export const mockGroups: MediaGroup[] = [
    {
        id: 'g-1',
        name: 'Website Assets',
        description: 'Images and videos for the main website',
        color: '#6366f1',
        icon: 'globe',
        allowed_roles: ['admin', 'developer', 'marketing'],
        created_by: '1',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'g-2',
        name: 'Marketing Materials',
        description: 'Social media, ads, and campaign assets',
        color: '#ec4899',
        icon: 'star',
        allowed_roles: ['admin', 'marketing'],
        created_by: '1',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'g-3',
        name: 'Product Images',
        description: 'Product photos and screenshots',
        color: '#10b981',
        icon: 'image',
        allowed_roles: ['admin', 'developer', 'marketing'],
        created_by: '1',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'g-4',
        name: 'Documentation',
        description: 'PDFs, guides, and documents',
        color: '#f59e0b',
        icon: 'file',
        allowed_roles: ['admin', 'developer'],
        created_by: '1',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];

// Sample images from Unsplash for demo
const sampleImages = [
    'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400',
    'https://images.unsplash.com/photo-1557683316-973673baf926?w=400',
    'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=400',
    'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=400',
    'https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?w=400',
    'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=400',
    'https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=400',
    'https://images.unsplash.com/photo-1618172193622-ae2d025f4032?w=400',
];

export const mockMedia: MediaWithDetails[] = Array.from({ length: 24 }, (_, i) => ({
    id: `m-${i + 1}`,
    storage_account_id: mockStorageAccounts[i % 3].id,
    media_group_id: mockGroups[i % 4].id,
    filename: `${['hero-banner', 'product-shot', 'team-photo', 'logo', 'background', 'icon', 'thumbnail', 'cover'][i % 8]}-${i + 1}.${i % 5 === 0 ? 'png' : 'jpg'}`,
    original_filename: `original-file-${i + 1}.jpg`,
    storage_key: `uploads/2024/${String(i + 1).padStart(6, '0')}`,
    media_type: i % 10 === 0 ? 'video' : i % 7 === 0 ? 'document' : 'image' as const,
    mime_type: i % 10 === 0 ? 'video/mp4' : i % 7 === 0 ? 'application/pdf' : 'image/jpeg',
    file_size_bytes: Math.floor(Math.random() * 5000000) + 100000,
    public_url: sampleImages[i % sampleImages.length],
    thumbnail_url: sampleImages[i % sampleImages.length],
    uploaded_by: '1',
    folder_path: i % 3 === 0 ? '/banners' : i % 3 === 1 ? '/products' : '/general',
    is_public: true,
    retention_policy: i % 4 === 0 ? 'temporary' : i % 4 === 1 ? 'project' : 'permanent',
    tags: ['demo', i % 2 === 0 ? 'featured' : 'standard'],
    download_count: Math.floor(Math.random() * 100),
    created_at: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    storage_account_name: mockStorageAccounts[i % 3].name,
    storage_provider: mockStorageAccounts[i % 3].provider,
    group_name: mockGroups[i % 4].name,
    uploader_name: 'Admin User',
}));

export const mockEmployees: Employee[] = [
    mockEmployee,
    {
        id: '2',
        email: 'dev@company.com',
        full_name: 'Sarah Developer',
        role: 'developer',
        is_active: true,
        last_login_at: new Date(Date.now() - 3600000).toISOString(),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '3',
        email: 'marketing@company.com',
        full_name: 'Mike Marketing',
        role: 'marketing',
        is_active: true,
        last_login_at: new Date(Date.now() - 7200000).toISOString(),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '4',
        email: 'viewer@company.com',
        full_name: 'View Only User',
        role: 'viewer',
        is_active: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];

// Audit log entries
export const mockAuditLogs = [
    { id: '1', action: 'upload', actor: 'Admin User', target: 'hero-banner-1.jpg', provider: 'Cloudinary', timestamp: new Date(Date.now() - 60000).toISOString() },
    { id: '2', action: 'delete', actor: 'Sarah Developer', target: 'old-logo.png', provider: 'R2', timestamp: new Date(Date.now() - 3600000).toISOString() },
    { id: '3', action: 'move', actor: 'Mike Marketing', target: 'campaign-video.mp4', provider: 'S3', timestamp: new Date(Date.now() - 7200000).toISOString() },
    { id: '4', action: 'upload', actor: 'Admin User', target: 'product-shot-5.jpg', provider: 'Cloudinary', timestamp: new Date(Date.now() - 10800000).toISOString() },
];
